apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: default
  destination:
    namespace: argocd
    name: in-cluster
  source:
    repoURL: git@github.com:Mohsen51/argocd-repo.git
    path: .
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
